<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container71QogBK\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container71QogBK/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container71QogBK.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container71QogBK\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \Container71QogBK\App_KernelDevDebugContainer([
    'container.build_hash' => '71QogBK',
    'container.build_id' => '18a1f0c6',
    'container.build_time' => 1623447754,
], __DIR__.\DIRECTORY_SEPARATOR.'Container71QogBK');
